apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: jodubranding
  labels:
    app: frontend
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/poll: 5m
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        kubernetes.io/hostname: o1k2
      containers:
      - name: frontend
        image: ghcr.io/timothechauvet/choose-your-username-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: PUBLIC_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: supabase-secret
              key: PUBLIC_SUPABASE_URL
        envFrom:
        - secretRef:
            name: supabase-secret
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
      imagePullSecrets:
      - name: ghcr-secret
