apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-yourls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-yourls
  template:
    metadata:
      labels:
        app: mysql-yourls
    spec:
      containers:
      - name: mysql-yourls
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: root-password
        - name: MYSQL_DATABASE
          value: yourls_db
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-yourls-pvc

