apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yourls
  template:
    metadata:
      labels:
        app: yourls
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      initContainers:
      - name: test-mysql
        image: mariadb:10.11
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        command: ['sh', '-c', 'set -x; until mariadb -h mysql-yourls --user="$MYSQL_USER" --password="$MYSQL_PASSWORD" -e "SELECT 1"; do echo "waiting for mysql at mysql-yourls"; sleep 2; done;']
      - name: create-index
        image: busybox
        command: ['sh', '-c', 'echo "<?php header(''Location: /admin/'');" > /var/www/html/index.php']
        volumeMounts:
        - name: html
          mountPath: /var/www/html
      containers:
      - name: yourls
        image: yourls:1.10.4-apache
        env:
        - name: APACHE_SERVER_NAME
          value: "tmth.fr"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /var/www/html/user/config.php
          subPath: config.php
        - name: html
          mountPath: /var/www/html
      volumes:
      - name: config
        configMap:
          name: yourls-config
      - name: html
        emptyDir: {}

