apiVersion: v1
kind: Service
metadata:
  name: jodubranding-nginx-service
  namespace: jodubranding
spec:
  type: ClusterIP
  selector:
    app: jodubranding-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
