apiVersion: v1
kind: Service
metadata:
  name: yasssf-frontend
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: yasssf-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
