apiVersion: v1
kind: ConfigMap
metadata:
  name: yourls-config
data:
  config.php: |
    <?php
    define( 'YOURLS_DB_USER', 'db_user' );
    define( 'YOURLS_DB_PASS', 'db_password' );
    define( 'YOURLS_DB_NAME', 'yourls_db' );
    define( 'YOURLS_DB_HOST', 'mysql-yourls' );
    define( 'YOURLS_SITE', 'https://tmth.fr' );
    define( 'YOURLS_HOURS_OFFSET', '5');
    define( 'YOURLS_UNIQUE_URLS',  'true');
    define( 'YOURLS_PRIVATE',  'true');
    define( 'YOURLS_COOKIEKEY', 'cookie_key' );
    define( 'YOURLS_URL_CONVERT',  '36');
    define( 'YOURLS_DB_PREFIX',  'yourls_');
    define( 'YOURLS_FLOOD_DELAY_SECONDS',  '0');
    define( 'YOURLS_LANG',  ''); 
    define( 'YOURLS_DEBUG', 'false');
    $yourls_reserved_URL = array(
      'activate',
      'admin',
      'api',
      'feed',
      'index.php',
      'install',
      'login',
      'logout',
      'page',
      'plugins',
      'readme.html',
      'register',
      'robots.txt',
      'rss',
      'upgrade',
      'yourls-api.php',
      'yourls-loader.php',
    );
    $yourls_user_passwords = array(
      'yourls_user' => 'yourls_password',
    );
