apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "timothechauvet",
          "password": "my_pat",
          "email": "timothe@chauvet.dev",
          "auth": "base64-code of timothechauvet:my_pat"
        }
      }
    }
