apiVersion: v1
kind: Secret
metadata:
  name: supabase-secret
  namespace: jodubranding
type: Opaque
stringData:
  PUBLIC_SUPABASE_ANON_KEY: "secret"
  SERVICE_ROLE_KEY: "secret"
  PUBLIC_SUPABASE_URL: "https://secret.supabase.co"
