apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: jodubranding
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "timothe",
          "password": "secret",
          "email": "timothe@chauvet.dev",
          "auth": "secret"
        }
      }
    }
